import {StyleSheet} from 'react-native';

import {Game_Background,
Game_Footer_Height,
Game_Events_Width,
Game_Events_Height,
Game_Events_Background,
Game_Footer_Turn_Width,
Game_Footer_Turn_Border_Background,
Game_Footer_Turn_BorderRadius,
Game_Footer_Turn_Background,
Game_Footer_Turn_BorderWidth,
Game_Events_BorderWidth,
Game_Events_BorderBackground,
Game_Events_BorderRadius,
Screen_Width} from '../../../styles/common.js';

export const styles=StyleSheet.create({
	Game:{
		backgroundColor: Game_Background,
		flex: 1,
		flexDirection: 'column',
		justifyContent: 'space-between',
		alignItems: 'center'
	},
	Header:{
		height: 50,
		backgroundColor: 'white',
		width: Screen_Width,
		borderBottomWidth: 5,
		borderBottomColor: 'red',
		borderStyle: 'solid',
		borderTopWidth: 5,
		borderTopColor: 'red',
		borderStyle: 'solid',
		justifyContent: 'center',
		alignItems: 'center'
	},
	Header_Text:{
		fontSize: 22,
		color: 'red',
	},
	Info:{
		flexDirection: 'row',
		backgroundColor: 'purple',
		justifyContent: 'space-around',
		width:Screen_Width,
	},
	Player:{
		height:160,
		width:150,
		backgroundColor: 'yellow',
		borderWidth: 5,
		borderColor: 'red',
		borderStyle: 'solid',
		borderRadius: 10,
	},
	Players:{
		height:250,
		width:200,
		backgroundColor: 'blue',
		borderWidth: 5,
		borderColor: 'red',
		borderStyle: 'solid',
		borderRadius: 10,
	},
	Events:{
		height: Game_Events_Height,
		width: Game_Events_Width,
		backgroundColor: 'red',
		borderWidth: Game_Events_BorderWidth,
		borderColor: Game_Events_BorderBackground,
		borderStyle: 'solid',
		borderRadius: Game_Events_BorderRadius,
	},
	Turns:{
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-around',
		width:Screen_Width,
		height:Game_Footer_Height,
		backgroundColor: 'green',
	},
	Turn:{
		height:Game_Footer_Turn_Width,
		width:Game_Footer_Turn_Width,
		backgroundColor: Game_Footer_Turn_Background,
		width: Game_Footer_Turn_Width,
		height: Game_Footer_Turn_Width,
		borderWidth: Game_Footer_Turn_BorderWidth,
		borderColor: Game_Footer_Turn_Border_Background,
		borderStyle: 'solid',
		borderRadius: Game_Footer_Turn_BorderRadius,
	}
});